### PR TITLE
Added colored mana symbol

### PR DESCRIPTION
**Pull request by jefperito**

### CODE REVIEW

**Comment by chigby** [comment]
Hi! Thanks for this feature. It's very cool, especially for multi-colored cards, and takes advantages of a terminal capability that this project hasn't used very much. There was actually a time when I was trying to figure out how to get the actual mana symbols to appear as images, but I gave up on that because it seemed too hard. This is a good compromise.

Here's a question I have: do you think that the command line argument should be a verb? I worry that `--colours` will possibly be confused with the `--color` option for searching cards by color. Maybe something like `--colourize`?

Also, this pull request has made me realize we really ought to have alternate option names for "color" and "colour" for other countries besides the US.

I'm happy to merge this request once we settle on the name of the option.

**Comment by jefperito** [comment]
Hi, i haven't full english yet, so i have some troubles with nomenclature and stuff :/
--colourize is fine to me.
I dont know "color" and "colour" have differences among countries.

i will fix it and pull the request again.

**Comment by jefperito** [comment]
its done.

Note: i cant run the unit tests, which the args to do it?

**Comment by chigby** [comment]
I've been using the command `nosetests` -- it requires you to install the package called `nose`: https://pypi.python.org/pypi/nose/

From my end, everything passes, so I'm just going to go ahead and merge it.

**Pull request merged**
